### PR TITLE
Fix and enhance PayPalPurchaseUnit

### LINKED ISSUE #215: Wrong attribute "invoice_number" is used
Hi,

**SyliusPayPalPlugin version affected**: v1.3.0

**Description**
During creation and updates of PayPal orders and payments there is used the attribute "invoice_number", this attribute got ignored from PayPal.

**Possible Solution**
According to the PayPal API doc the attribute should be named "invoice_id"
- payments: https://developer.paypal.com/docs/api/payments/v2/#captures-refund-request-body
- orders: https://developer.paypal.com/docs/api/orders/v2/#definition-purchase_unit_request

This has to be changed in the following files:
- [Sylius\PayPalPlugin\Client\PayPalClientInterface\RefundPaymentApi](https://github.com/Sylius/PayPalPlugin/blob/master/src/Api/RefundPaymentApi.php)
- [Sylius\PayPalPlugin\Api\CreateOrderApi](https://github.com/Sylius/PayPalPlugin/blob/master/src/Api/CreateOrderApi.php)
- [Sylius\PayPalPlugin\Api\UpdateOrderApi](https://github.com/Sylius/PayPalPlugin/blob/master/src/Api/UpdateOrderApi.php)

### PR DESCRIPTION
**Pull request by maikrosenthal**
| Q               | A
| --------------- | -----
| Branch?         | 1.6 (bug fixes, improvements)
| Bug fix?        | yes
| New feature?    | no
| Related tickets | fixes #215

This will fix the wrong attribute "invoice_number" and add the "shipping_discount" to PayPalPurchaseUnit

### CODE REVIEW

File: src/Api/RefundPaymentApi.php [hunk 1]
```diff
@@ -28,14 +28,14 @@ public function refund(
         string $token,
         string $paymentId,
         string $payPalAuthAssertion,
-        string $invoiceNumber,
+        string $invoiceId,
```
Comment (GSadee) [inline src/Api/RefundPaymentApi.php]: I would be for not changing the argument name, as it could be a potential BC Break:
```suggestion
        string $invoiceNumber,
```

File: src/Model/PayPalPurchaseUnit.php [hunk 2]
```diff
@@ -18,80 +18,29 @@
...
-        float $itemTotalValue,
-        float $taxTotalValue,
-        int $discountValue,
-        string $merchantId,
-        array $items,
-        bool $shippingRequired,
-        ?AddressInterface $shippingAddress = null,
-        string $softDescriptor = 'Sylius PayPal Payment',
+        private readonly string $referenceId,
+        private readonly string $invoiceId,
```
Comment (GSadee) [inline src/Model/PayPalPurchaseUnit.php]: As above, do not change the argument name

File: src/Model/PayPalPurchaseUnit.php [hunk 3]
```diff
@@ -18,80 +18,29 @@
...
+        private readonly string $currencyCode,
+        private readonly int $totalAmount,
+        private readonly int $shippingValue,
+        private readonly float $itemTotalValue,
+        private readonly float $taxTotalValue,
+        private readonly int $discountValue,
+        private readonly int $shippingDiscountValue,
```
Comment (GSadee) [inline src/Model/PayPalPurchaseUnit.php]: Add this new argument as the optional one at the end and add the note to the UPGRADE file

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, @maikrosenthal! :tada:
