### PR TITLE
[Shop] Fix paypal checkout when another payment method was selected during checkout

### LINKED ISSUE #303: [Bug] Customer changes payment method later
**SyliusPayPalPlugin version affected**: 1.6.0

**Description**  
If the customer puts a few items in the shopping cart and wants to pay with e.g. ‘Cash on Delivery’ but then changes his mind and wants to pay with PayPal Express Checkout, this does not work. It runs into an error.

**Steps to reproduce**  
- Add an item to your shopping cart
- Select payment method ‘Cash on Delivery
- Go to the last step ‘Checkout Complete’ but do not finalise the order
- Go back to the shopping basket or product detail page and click on Paypal Express Checkout.
- Now it runs into an error.

### PR DESCRIPTION
**Pull request by Wojdylak**
| Q               | A
| --------------- | -----
| Branch?         | 1.6
| Bug fix?        | yes
| New feature?    | no
| Related tickets | fixes #303

### CODE REVIEW

File: src/Controller/CreatePayPalOrderFromCartAction.php [hunk 1]
```diff
@@ -94,4 +113,24 @@ public function __invoke(Request $request): Response
...
+            }
+
+            $this->orderPaymentsRemover->removePayments($order);
+            $this->orderProcessor->process($order);
+
+            $payment = $order->getLastPayment(PaymentInterface::STATE_CART);
+        }
+
+        return $payment;
+    }
```
Comment (NoResponseMate) [inline src/Controller/CreatePayPalOrderFromCartAction.php]:
```suggestion
    private function getPaypalPayment(OrderInterface $order): PaymentInterface
    {
        /** @var PaymentInterface $payment */
        $payment = $order->getLastPayment(PaymentInterface::STATE_CART);
        $factoryName = $payment->getMethod()?->getGatewayConfig()?->getFactoryName();

        if ($factoryName === 'sylius.pay_pal') {
            return $payment;
        }

        if ($this->orderPaymentsRemover === null || $this->orderProcessor === null) {
            throw new \DomainException('OrderPaymentsRemover and OrderProcessor must be provided to create a new payment.');
        }

        $this->orderPaymentsRemover->removePayments($order);
        $this->orderProcessor->process($order);

        return $order->getLastPayment(PaymentInterface::STATE_CART);
    }
```

File: src/Controller/CreatePayPalOrderFromCartAction.php [hunk 2]
```diff
@@ -94,4 +113,24 @@ public function __invoke(Request $request): Response
...
+        $payment = $order->getLastPayment(PaymentInterface::STATE_CART);
+        $factoryName = $payment->getMethod()?->getGatewayConfig()?->getFactoryName();
+
+        if ($factoryName !== 'sylius.pay_pal') {
+            if ($this->orderPaymentsRemover === null || $this->orderProcessor === null) {
+                throw new \DomainException('OrderPaymentsRemover and OrderProcessor must be provided to create a new payment.');
+            }
+
+            $this->orderPaymentsRemover->removePayments($order);
+            $this->orderProcessor->process($order);
```
Comment (NoResponseMate) [inline src/Controller/CreatePayPalOrderFromCartAction.php]: Add a comment as to why this is necessary/wat it do

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -193,7 +193,7 @@ jobs:
 
             -
                 name: Upload Behat logs
-                uses: actions/upload-artifact@v2
```
Comment (NoResponseMate) [inline .github/workflows/build.yml:196]: Since we're moving to v4, add an `overwrite: true` option

File: src/Controller/CreatePayPalOrderFromCartAction.php [hunk 4]
```diff
@@ -66,19 +71,33 @@ public function __construct(
                 ),
             );
         }
+        if (null === $this->orderPaymentsRemover) {
+            trigger_deprecation(
+                'sylius/paypal-plugin',
+                '1.6',
+                'Not passing an $orderPaymentsRemover to %s constructor is deprecated and will be prohibited in 2.0',
```
Comment (GSadee) [inline src/Controller/CreatePayPalOrderFromCartAction.php]:
```suggestion
                'Not passing an $orderPaymentsRemover to %s constructor is deprecated and will be prohibited in 3.0',
```
as 2.0 is already released and there will be the same backward compatibility problem

File: src/Controller/CreatePayPalOrderFromCartAction.php (hunk 2 above)
Comment (Wojdylak) [reply src/Controller/CreatePayPalOrderFromCartAction.php]: I think the test I added provides a good comment explaining the code I added.

**Review by mpysiak — APPROVED** [review]

File: tests/Functional/CreatePayPalOrderFromCartActionTest.php [hunk 5]
```diff
@@ -33,4 +33,21 @@ public function it_creates_pay_pal_order_from_cart_and_returns_its_data(): void
         $this->assertSame($content['orderID'], 'PAYPAL_ORDER_ID');
         $this->assertSame($content['status'], 'cart');
     }
+
+    /** @test */
+    public function it_creates_pay_pal_order_from_cart_and_returns_its_data_if_payment_method_is_different_then_pay_pal(): void
```
Comment (GSadee) [inline tests/Functional/CreatePayPalOrderFromCartActionTest.php:38]:
```suggestion
    public function it_creates_paypal_order_from_cart_and_returns_its_data_if_payment_method_is_different_than_paypal(): void
```

**Review by GSadee — APPROVED** [review]
