### PR TITLE
[ExpressCheckout] Get paypal methods directly instead of defaulting

### LINKED ISSUE #302: [Bug] Default Payment Method
**SyliusPayPalPlugin version affected**: 1.6.0

**Description**  
Our customers can set their preferred payment method as the default payment method. We have written the code for this ourselves.

However, this conflicts with the PayPal Express Checkout, as it seems to assume that PayPal is always the default payment method. The checkout fails.

**Steps to reproduce**  

- Set payment in the current shopping cart to a payment method other than ‘PayPal’ (via the database) 
- Try PayPal Express Checkout

**Possible Solution**  
Modify the `CreatePayPalOrderFromCartAction` so that the payment method is changed to PayPal?

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | kinda?
| Related tickets | fixes #302

### CODE REVIEW

File: src/Resolver/PayPalPaymentMethodsResolver.php [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+use Sylius\Component\Core\Model\ChannelInterface;
+use Sylius\Component\Core\Model\PaymentMethodInterface;
+use Sylius\Component\Core\Repository\PaymentMethodRepositoryInterface;
+use Sylius\PayPalPlugin\DependencyInjection\SyliusPayPalExtension;
+
+final class PayPalPaymentMethodsResolver implements PayPalPaymentMethodsResolverInterface
+{
+    public function __construct(
+        private PaymentMethodRepositoryInterface $paymentMethodRepository,
```
Comment (GSadee) [inline src/Resolver/PayPalPaymentMethodsResolver.php]:
```suggestion
        private readonly PaymentMethodRepositoryInterface $paymentMethodRepository,
```

**Review by GSadee — APPROVED** [review]

**Review by GSadee — APPROVED** [review]
