### PR TITLE
Fix line items creation being tied with the number of taxes

### LINKED ISSUE #367: [Bug] Multiple taxes cause order item duplication in PayPal request.
**SyliusPayPalPlugin version affected**: 1.x.y

**Description**  
Multiple taxes cause items duplication. When order item has more than one TAX_ADJUSTMENT (in USA there even can be 4 different taxes applied, in Canda  two different taxes) it is duplicated as many time as many taxes are assigned.

**Steps to reproduce**  
Create order with OrderItem that has two TAX_ADJUSTMENT. Then try to pay for an order with paypal plugin.
In file: vendor/sylius/paypal-plugin/src/Provider/PayPalItemDataProvider.php on line 38 plugin takes all non neutral adjustments:
```
$nonNeutralTaxes = $this->orderItemNonNeutralTaxesProvider->provide($orderItem);
```
next it will iterate over adjustment and duplicate order item for every non-neutral tax adjustment:
```
         foreach ($nonNeutralTaxes as $nonNeutralTax) {
                $displayQuantity = $nonNeutralTaxes === [0] ? $orderItem->getQuantity() : 1;
                $itemValue = $orderItem->getUnitPrice();
                $itemData['total_item_value'] += ($itemValue * $displayQuantity) / 100;
                $itemData['total_tax'] += ($nonNeutralTax * $displayQuantity) / 100;

                $itemData['items'][] = [
                    'name' => $orderItem->getProductName(),
                    'unit_amount' => [
                        'value' => number_format($itemValue / 100, 2, '.', ''),
                        'currency_code' => $order->getCurrencyCode(),
                    ],
                    'quantity' => $displayQuantity,
                    'tax' => [
                        'value' => number_format($nonNeutralTax / 100, 2, '.', ''),
                        'currency_code' => $order->getCurrencyCode(),
                    ],
                ];
            }
```

**Possible Solution**  
We should not assume that there can be only one tax like in Europe.
$itemData['items'][] - should be called for order items not for the adjustment.

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no?
| Related tickets | fixes #367, replaces #298

### CODE REVIEW

File: spec/Provider/OrderItemNonNeutralTaxesProviderSpec.php [hunk 1]
```diff
@@ -42,4 +42,153 @@ function it_provides_non_neutral_tax_based_on_given_order_item(
 
         $this->provide($orderItem)->shouldReturn([20]);
     }
+
+    function it_returns_empty_array_when_no_taxes_exist(
```
Comment (GSadee) [inline spec/Provider/OrderItemNonNeutralTaxesProviderSpec.php:46]: You could have already written new tests in PHPUnit, because we migrated from phpspec in 2.x anyway

**Review by GSadee — APPROVED** [review]

File: spec/Provider/OrderItemNonNeutralTaxesProviderSpec.php (hunk 1 above)
Comment (NoResponseMate) [reply spec/Provider/OrderItemNonNeutralTaxesProviderSpec.php:46]: Either way, it'll require additional work on upmerge 🤷
