### PR TITLE
Check order has a shipping address in the PayPalAddressProcessor

### LINKED ISSUE #157: Take in account orders without shipping address
For example for products that are digital subscriptions that don't need to be shipped

Actually [PayPalAddressProcessor](https://github.com/Sylius/PayPalPlugin/blob/master/src/Processor/PayPalAddressProcessor.php) fails if order hasn't a shipping address.

### PR DESCRIPTION
**Pull request by jdeveloper**
Fixes #157

### CODE REVIEW

File: src/Processor/PayPalAddressProcessor.php [hunk 1]
```diff
@@ -24,9 +24,13 @@ public function __construct(ObjectManager $objectManager)
      */
     public function process(array $address, OrderInterface $order): void
     {
-        /** @var AddressInterface $orderAddress */
+        /** @var ?AddressInterface $orderAddress */
         $orderAddress = $order->getShippingAddress();
 
+        if (null == $orderAddress) {
```
Comment (Zales0123) [inline src/Processor/PayPalAddressProcessor.php:30]: We should always use a strict comparison `===`

**Review by Zales0123 — COMMENTED** [review]
👍

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
Thanks, @jdeveloper! :1st_place_medal:
