### PR TITLE
Fix performance issue of getting all payments within the payment flow

### LINKED ISSUE #247: Cancel state order not working proprely if table sylius_payment is too big
**SyliusPayPalPlugin version affected**: master

**Description**  
Hi everyone, i had a problem with the cancelation or abort payment step. I have a big database sylius with about more 400000 entries into 'sylius_payment' table. During the cancel process to get all payments, the retriving the id transaction paypal take so much time that cannot work proprely. That redirect me to the payment methods page without the 'cancelled' state or worst get an error 500 'OutofMemory' if you had limited in memory PHP. If i go to the payment methods page, i can't go re-attempt to validate an another transaction.

**Steps to reproduce**  
- Try to get more 10000 entries in 'sylius_payment' table
- Go to the popin Paypal Checkout and click to 'Cancel and return to Test Store' or exit the popin to trigger the cancel state.
- See the time between line 32 - 34 in PaymentProvider.php (too long)

**Possible Solution**  
- Create a new route, like create and complete route, with the orderid sylius
- Pass this new route into PaypalButtonsController.php (line 139) with the orderid sylius
- Modify CancelPaypalPaymentAction line 29 -31 to retrieve the order sylius and the last payment.

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| Related tickets | fixes #247, replaces #248

### CODE REVIEW

File: src/Repository/Query/PaypalPaymentQuery.php [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+use Sylius\PayPalPlugin\Exception\PaymentNotFoundException;
+
+final class PaypalPaymentQuery implements PaypalPaymentQueryInterface
+{
+    public function __construct(
+        private readonly EntityManagerInterface $entityManager,
+        private readonly PaymentRepositoryInterface $paymentRepository,
+        private readonly array $updatableStates = ['cart', 'new', 'processing'],
+        private readonly array $cancellableStates = ['cart', 'new', 'processing', 'completed'],
+        private readonly array $refundableStates = ['completed'],
```
Comment (GSadee) [inline src/Repository/Query/PaypalPaymentQuery.php:30]: I wonder if this should not be taken from the state machine in some way, so that these states remain consistent 🤔

File: src/Controller/Webhook/RefundOrderAction.php [hunk 2]
```diff
@@ -53,7 +55,11 @@ public function __invoke(Request $request): Response
         $refundData = $this->payPalRefundDataProvider->provide($this->getPayPalPaymentUrl($request));
 
         try {
-            $payment = $this->paymentProvider->getByPayPalOrderId((string) $refundData['id']);
+            if (null !== $this->paypalPaymentQuery) {
+                $payment = $this->paypalPaymentQuery->getForRefundingByOrderId((string) $refundData['id']);
+            } else {
+                $payment = $this->paymentProvider->getByPayPalOrderId((string) $refundData['id']);
```
Comment (GSadee) [inline src/Controller/Webhook/RefundOrderAction.php:61]: I believe that this service could be deprecated, but preferably in 2.1 🤔

**Review by GSadee — APPROVED** [review]

File: src/Repository/Query/PaypalPaymentQuery.php (hunk 1 above)
Comment (NoResponseMate) [reply src/Repository/Query/PaypalPaymentQuery.php:30]: From what I've searched, there's no way to do that, except by getting the configuration directly (and that's different depending on the used state machine). It might be worth adding something like that directly to the abstraction layer within Sylius.

File: src/Controller/Webhook/RefundOrderAction.php (hunk 2 above)
Comment (NoResponseMate) [reply src/Controller/Webhook/RefundOrderAction.php:61]: Added in #398 👋
